-- Initial schema for parent accounts and child profiles.
-- Intended for MySQL 8.4.
-- Password hashes must be generated by the backend.

CREATE DATABASE IF NOT EXISTS project18
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_0900_ai_ci;

USE project18;

CREATE TABLE IF NOT EXISTS parent_accounts (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    CONSTRAINT uq_parent_email UNIQUE (email)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS child_profiles (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    parent_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(100) NOT NULL,
    age TINYINT UNSIGNED NOT NULL,
    CONSTRAINT fk_child_parent
        FOREIGN KEY (parent_id)
        REFERENCES parent_accounts(id),
    CONSTRAINT chk_child_age
        CHECK (age BETWEEN 10 AND 12)
) ENGINE=InnoDB;
